apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: metrics-app-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: metrics-app
  minReplicaCount: 2
  maxReplicaCount: 10
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://kube-prom-stack-kube-prome-prometheus.monitoring.svc:9090
        metricName: nginx_requests_per_second
        query: sum(rate(nginx_http_requests_total[30s]))
        threshold: "5"
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0     # UNTUNED: react instantly to spikes
          policies:
            - type: Percent
              value: 100
              periodSeconds: 15
        scaleDown:
          stabilizationWindowSeconds: 0     # UNTUNED: scale down instantly too — this causes flapping under bursty traffic
          policies:
            - type: Percent
              value: 100
              periodSeconds: 15
