apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-stress-before
  namespace: default
spec:
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: noisy-neighbor
  stressors:
    cpu:
      workers: 16
      load: 100
  duration: "120s"
