apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: metrics-app-packet-loss
  namespace: default
spec:
  action: loss
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      app: metrics-app
  loss:
    loss: "25"
  duration: "40s"
