apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: metrics-app-network-chaos
  namespace: default
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      app: metrics-app
  delay:
    latency: "500ms"
    jitter: "100ms"
  duration: "40s"
